export const Data = [
    {
        id: 1,
        category: 'Desserts',
        recipeName: 'Cookie Butter Brown Sugar Slab Pie',
        ingredients: ['2 ½ prepared single pie crusts (storebought or homemade), ½ cup cookie butter spread (like Biscoff), plus more for decorating, ½ cup dark brown sugar, 1 Tbsp all-purpose flour, 2 tsp cinnamon, divided, ½ tsp fine sea salt, 1 egg, 1 ½ cups powdered sugar, 1-2 Tbsp milk, ½ tsp vanilla extract'],
        directions: 'Step 1: Preheat oven to 375°F. Roll out half the amount of pie dough into a rectangle, about 12 x 16-inches. Line the bottom of a 9 x 13-inch quarter sheet pan with parchment paper. Fit the dough into the pan. Allow an inch or so of dough to overhang the edges. Step 2: Scoop ½ cup of the cookie butter onto the dough. Spread with a spatula to cover the dough. Step 3: In a small bowl, stir together the brown sugar, flour, 1 ½ teaspoons cinnamon and salt. Step 4: Sprinkle the sugar mixture all over the cookie butter. Step 5: Roll out the second half of the dough into a rectangle, about 11 x 15-inches. Whisk the egg with a splash of water to create an egg wash. Brush the edges of the bottom piece of dough with egg wash. Step 6: Place the second piece of dough on top of the pie, pressing the edges together to seal. Trim the edges as needed. Crimp the edges together. Pierce the top of the pie with a paring knife a few times then brush all over with the egg wash. Step 7: Set the pie on top of a large rimmed baking sheet and into the oven. Bake for about 35 minutes, or until puffed and golden brown. Allow to cool before adding the glaze. Step 8: To make the glaze, stir together the powdered sugar, ½ tsp cinnamon, 1 tablespoon milk, and vanilla extract. The glaze should be smooth and pourable, but not runny. Add more milk as needed. Step 9: Spoon the glaze onto the cooled pie. Fill a piping bag (or a zip-top plastic bag with the corner snipped off) with a scoop of cookie butter. Squeeze the cookie butter over the top of the glaze. Step 10: Slice and enjoy!'
    },
    {
        id: 2,
        category: 'Dinner',
        recipeName: 'Ricotta Gnocchi',
        ingredients: ['Kosher salt, 2 cups ricotta cheese, 1/2 cup grated Parmesan, 1 1/2 tablespoons extra-virgin olive oil, 2 large eggs, 1 1/4 cups all-purpose flour, plus more for dusting, Semolina flour, for dusting, Pancetta Tomato Sauce, recipe follows, for serving, Pancetta Tomato Sauce: 6 ounces thick-cut pancetta (about 3 1/4-inch slices), diced, 1/2 cup diced onions, Kosher salt and freshly ground black pepper, 2 cloves garlic, minced, One 28-ounce can crushed San Marzano tomatoes, 5 fresh basil leaves, cut into chiffonade'],
        directions: 'Step 1: Bring a large pot of salted water to a boil. Step 2: Combine the ricotta cheese, Parmesan, olive oil, eggs and 1 teaspoon salt with a whisk in a large mixing bowl. Add the all-purpose flour in 3 parts, stirring with a rubber spatula. Step 3: Bring the dough together in a ball and cut off one-quarter of it. Dust the work surface with all-purpose flour to prevent sticking, and roll the cut-off piece of dough into a dowel shape about 5/8 inch in diameter. Cut the dowel into 5/8-inch pieces. Dust some parchment paper with semolina flour and place the gnocchi on it to prevent sticking. Repeat with the rest of the dough, quarter by quarter. Step 4: Cook the gnocchi in the boiling water for 2 minutes. Serve tossed with a bit of the Pancetta Tomato Sauce. Alternatively, you can freeze the uncooked gnocchi for up to 2 weeks. Step 5: Heat a large saute pan over medium-high heat. Add the pancetta and cook until the fat has rendered and the pancetta is crisp, about 5 minutes. Remove the pancetta from the pan and reserve, leaving the fat behind. Step 6: Add the diced onions to the hot pan and season with salt and pepper. Cook until the onions have softened, about 5 minutes. Add the garlic and cook 1 minute more. Add the crushed tomatoes, cover and bring to a simmer. Cook for 20 minutes, then remove the lid, add the reserved pancetta and cook an additional 10 minutes. Season with additional salt and pepper, stir in the basil and serve.'
    },
    {
        id: 3,
        category: 'Breakfast',
        recipeName: 'Nordic Breakfast Porridge',
        ingredients: ['Barley Porridge: 2 1/2 cups whole milk, 1 cup barley flakes, 2 tablespoons light brown sugar, 1 tablespoon unsalted butter, Kosher salt. Toppings: 1 pint raspberries, 1 tablespoon light brown sugar, 1/2 Granny Smith apple, cut into matchsticks, 2 tablespoons roasted pistachios, chopped, 4 teaspoons chia seeds, covered in 1 tablespoon water, 1/4 cup whole milkGround cinnamon, for sprinkling.'],
        directions: 'Step 1: For the barley porridge: Gently bring the milk and barley flakes to a boil over medium heat in a medium saucepan. Reduce the heat to a simmer, then cover and cook until the milk is almost absorbed and the barley is super soft and still a bit creamy, about 15 minutes. Stir in the sugar, butter and 1/2 teaspoon salt. Step 2: For the toppings: Meanwhile, roughly smash the raspberries with the sugar in a small bowl with a fork. Step 3: Divide the porridge among 4 bowls. Working around the edges of the bowls, make neat piles of the toppings, placing a quarter of the crushed raspberries, apple sticks, pistachios and chia seeds in each bowl. Drizzle each with 1 tablespoon milk and sprinkle with some cinnamon to finish.'
    },
    {
        id: 4,
        category: 'Breakfast',
        recipeName: 'Healthy Blueberry-Carrot Muffins',
        ingredients: ['Cooking spray, 1 1/2 cups blueberries, 2 cups whole wheat pastry flour or white whole wheat flour, 2 teaspoons baking powder, 1 teaspoon ground cinnamon, 1/2 teaspoon fine salt, 1/2 cup 2-percent lowfat milk, 1/2 cup melted virgin or extra-virgin coconut oil, 1/2 cup packed light-brown sugar, 2 medium carrots, shredded and squeezed dried, 2 large eggs, 1 teaspoon finely grated lemon zest, 1 teaspoon pure vanilla extract, 1 tablespoon turbinado sugar'],
        directions: 'Step 1: Position an oven rack in the middle of the oven and preheat to 350 degrees F. Line a 12-cup muffin pan with paper liners and spay the liners lightly with cooking spray. Step 2: Reserve 1/2 cup of the blueberries for garnish. Place the remaining blueberries in a large bowl and lightly crush them with the back of a fork (crushing keeps them from sinking to the bottom of the muffin batter during baking). Add the flour, baking powder, cinnamon and salt to the blueberries and stir to combine. Whisk together the milk, oil, brown sugar, carrots, eggs, lemon zest and vanilla in another bowl, whisking until no clumps of brown sugar remain. Fold the milk mixture into the flour mixture until just combined. Step 3: Divide the batter evenly among the prepared muffin cups. Press the reserved blueberries into the tops of the muffins. Bake for 10 minutes. Remove the pan from the oven and sprinkle the tops of the muffins with the turbinado sugar. Rotate the pan and continue to bake until the muffins are golden and a toothpick inserted in the centers comes out clean, 20 to 24 minutes. Cool the muffins in the pan for a few minutes, then transfer the muffins to a rack to cool completely.',
    },
    {
        id: 5,
        category: 'Dinner',
        recipeName: 'Lightened-Up Shepherds Pie',
        ingredients: ['1 pound all-purpose potatoes, peeled and quartered, 1 medium head cauliflower (about 2 pounds), cored and cut into 1-inch florets, 1 bunch scallions, finely chopped, 1 1/4 cups low-sodium chicken broth, Kosher salt and freshly ground black pepper, 1 pound lean ground beef, 1 teaspoon extra-virgin olive oil, 3 carrots, halved lengthwise and cut into thin half-moons, 3 cloves garlic, finely chopped, 2 stalks celery, finely chopped, 2 medium onions, finely chopped, 2 tablespoons all-purpose flour, 2 tablespoons tomato paste, 2 tablespoons Worcestershire sauce, One 10-ounce package frozen peas, thawed.'],
        directions: 'Step 1: Put the potatoes in a large saucepan and add enough cold water to cover by 2 inches. Bring to a boil, cover and reduce the heat to maintain a steady simmer. Cook until a knife just pierces through the potatoes, about 7 minutes. Add the cauliflower, bring to a boil and simmer until a knife easily slides through the vegetables, about 20 minutes. Reserve 1 cup of the cooking water before draining. Step 2: Return the potatoes and cauliflower to the saucepan. Add the scallions and mash with a potato masher. Add 1/ 4 cup of the broth and continue mashing until almost smooth. If the mixture is dry and falling apart, add a few spoonfuls of the cooking water and continue mashing. The mixture should be thick and hold together. Season with salt and pepper. Step 3: Meanwhile, preheat the oven to 425 degrees F. Heat a large skillet over medium-high heat until hot. Add the beef and spread out in a single layer. Sprinkle with salt and pepper. Cook, stirring and breaking into small bits, until browned, about 3 minutes. Transfer to a dish with a slotted spoon. Step 4: Add the oil to the same skillet and reduce the heat to medium. Add the carrots, garlic, celery, onions and some salt and pepper. Cook, stirring occasionally, until the vegetables are browned and tender, about 10 minutes. Add the flour and tomato paste and cook, stirring, for 1 minute. Stir in the Worcestershire sauce and remaining 1 cup broth. Bring to a boil, and then stir in the peas and the beef and its accumulated juices. Remove from the heat. Step 5: In a 3-quart ceramic flameproof baking dish, spread the beef mixture in an even layer. Spoon the potato mixture evenly on top. Bake until the beef mixture is bubbling, about 20 minutes. Turn the oven to broil and broil until the top is golden brown, about 5 minutes more. Let rest 5 minutes before serving.'
    },
    {
        id: 6,
        category: 'Desserts',
        recipeName: 'Lighter Cheesecake Brownies',
        ingredients: ['Cheesecake topping: 8 ounces reduced-fat cream cheese (Neufchatel), 1/3 cup sugar, 1/2 teaspoon vanilla extract, 1 large egg Brownie Layer: 2 ounces semisweet chocolate, coarsely chopped, 3 tablespoons unsalted butter, 2 tablespoons canola oil, 1 cup all-purpose flour, 1/2 cup unsweetened Dutch-process cocoa powder, 1 teaspoon baking powder, 1/2 teaspoon fine sea salt, Pinch cayenne pepper, 3/4 cup packed dark brown sugar, 1/4 cup granulated sugar, 1/2 cup lowfat buttermilk, 2 large egg whites, 2 teaspoons vanilla extract'],
        directions: 'Step 1: Position the rack in the lower third of the oven and preheat the oven to 350 degrees F. Step 2: Line an 8 by 8-inch baking pan with foil so it hangs over the edges by about 1-inch. Spray with cooking spray. Step 3: Cheesecake topping: In a medium bowl and using an electric mixer at medium speed, beat the cream cheese until smooth and creamy, about 1 minute. Beat in the sugar and the vanilla until very smooth, 1 to 2 minutes. Beat in the egg until well blended. Set aside. Step 4: Brownie layer: Put the chocolate, butter, and oil in a small microwave-safe bowl and heat at 75 percent power for 30 seconds. Stir and microwave again until melted and smooth, about 30 seconds longer. (Alternatively, put the chocolate, butter, and oil in a small heatproof bowl. Bring a small saucepan filled with 1 inch or so of water to a very slow simmer; set the bowl over, not touching, the water, and stir occasionally, until melted and smooth.) Step 5: Combine the flour, cocoa powder, baking powder, salt, and cayenne in a medium bowl. Step 6: Combine the brown sugar and granulated sugar in a large bowl. Whisk in the buttermilk, egg whites, and vanilla. Add the chocolate mixture and whisk vigorously until fully incorporated and the batter is thick and glossy. Gradually add the flour mixture and stir just until it disappears. Step 7: Reserve 1/2 cup brownie batter and set aside. Scrape the remaining brownie batter into the prepared pan. Pour the cheesecake mixture evenly over top. Drop the reserved brownie batter in large dollops over the topping. Draw the handle of a wooden spoon through the two batters to create a swirled effect. Step 8: Bake until the top is just set, 40 to 45 minutes. Let cool completely in the pan on a wire rack. Lift brownies out of the pan by the foil and peel off the foil. Spray a knife with cooking spray and cut into 2-inch squares.'
    },
];

export const Buttons = [
    {
        name: 'Breakfast',
        value: 'Breakfast',
    },
    {
        name: 'Dinner',
        value: 'Dinner',
    },
    {
        name: 'Desserts',
        value: 'Desserts',
    },
];

